//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OutlookPushoverAlerter
{
    [global::Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObjectAttribute(0)]
    partial class ThisAddIn : global::Microsoft.Office.Tools.Outlook.OutlookAddInBase
    {

        // Host item populated in Initialize(); the Outlook Application object.
        internal global::Microsoft.Office.Interop.Outlook.Application Application;

        /// <summary>
        /// Required by Visual Studio generated code. Do not modify.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ThisAddIn(global::Microsoft.Office.Tools.Outlook.Factory factory, global::System.IServiceProvider serviceProvider) :
                base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Globals.ThisAddIn = this;
            global::System.Windows.Forms.Application.EnableVisualStyles();
        }

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void Initialize()
        {
            base.Initialize();
            this.Application = this.GetHostItem<global::Microsoft.Office.Interop.Outlook.Application>(
                typeof(global::Microsoft.Office.Interop.Outlook.Application), "Application");
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void FinishInitialization()
        {
            this.InternalStartup();
            this.HookInbox();
        }
    }

    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Tools.Office", "16.0.0.0")]
    internal sealed partial class Globals
    {

        private Globals()
        {
        }

        private static ThisAddIn _ThisAddIn;

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal static ThisAddIn ThisAddIn
        {
            get
            {
                return _ThisAddIn;
            }
            set
            {
                if ((_ThisAddIn == null))
                {
                    _ThisAddIn = value;
                }
                else
                {
                    throw new global::System.NotSupportedException();
                }
            }
        }
    }
}
